//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MYKINGDOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        public int MaKhoHang { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
