//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MYKINGDOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoanKhachHang
    {
        public int MaTaiKhoan { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tài khoản")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        public string MatKhau { get; set; }
        public int MaKhachHang { get; set; }
        public string HoatDong { get; set; }

        public virtual KhachHang KhachHang { get; set; }
    }
}
