//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MYKINGDOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherKhachHang
    {
        public int MaVoucherKhachHang { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaVoucher { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
